FROM nginx

# Copy the default.conf nginx configaration to the container
# Basically override container /etc/nginx/conf.d/default.conf 
# with local ./default.conf file
COPY ./default.conf /etc/nginx/conf.d/default.conf