FROM node:alpine

WORKDIR '/app'

COPY ./package.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# To run
# "." is the build context, i.e. the client folder in this case
# docker build -f Dockerfile.dev .
# 